### ISSUE TITLE
Intersection points of two hyperbola.

### ISSUE THREAD

**Issue by quanhinh9** [vectorgraphics/asymptote#118]
I have problem when I find intersection points of two hyperbola in asymptote:

https://tex.stackexchange.com/questions/511077/intersectionpoints-of-two-hyperbola-in-asymptote

**Comment by johncbowman** [comment]
The problem was due to a numerical degeneracy in intersectionpoints(bqe bqe1, bqe bqe2).
A good way to avoid such problems is to transform the conic sections so that one of them is 
in canonical form. This has the added benefit that the coefficients of the quartic root solve simplify. The fix is in git and will be in the 2.57 release. Perhaps you can update your posting on stackexchange to show the correct result. Thanks for reporting this.
