### ISSUE TITLE
Error on cygwin?

### ISSUE THREAD

**Issue by quanhinh9** [vectorgraphics/asymptote#122]
I write asymptote code and get errors:

> Process started: "C:/Program Files (x86)/Asymptote/asy.exe" chaos1-1.asy

> Too many heap sections

> 1 [main] asy 8188 cygwin_exception::open_stackdumpfile: Dumping stack trace to asy.exe.stackdump

> Process exited with error(s)

My code:

`real x, r, step;
x=0.5; step=0.01;

for (r = 2.8; r < 4; r = r + step){
	for (int i = 0; i < 500; ++i){
		x = r * x * (1 - x);
		pair p=(r,x);
		dot(p,0.5bp+0.5cyan);
	}			
}`

**Comment by johncbowman** [comment]
I was only able to reproduce this with the 32-bit version of asy, so probably you inadvertently installed the 32-bit version instead of the 64-bit version. Almost all laptops and desktops are 64 bit nowadays. So the easiest fix is to install the normal
asymptote-2.61-setup.exe  binary. This 64-bit version is faster and has much better garbage collection.

If for some reason you are installing on legacy 32-bit hardware, you may find the discussion in the following link helpful. In particular, adding the flag -compact to the command line solves the problem when running your example with 32-bit asy under MSWindows 10. 

https://sourceforge.net/p/asymptote/discussion/409349/thread/5a91460c/

By the way, it is not a good idea to use floats as loop indices, if you care about how many times the loop will get executed.

**Comment by quanhinh9** [comment]
Thanks johncbowman,

I don't find version 64-bit for Windows: https://sourceforge.net/projects/asymptote/files/2.61/

In TexStudio 2019, I find asy.exe 64-bit in C:\texlive\2019\tlpkg\asymptote64. It complier more loop vs asymptote-2.61-setup-i386_32.exe.

**Comment by johncbowman** [comment]
Check again...it is there.

**Comment by asmwarrior** [comment]
> I don't find version 64-bit for Windows: https://sourceforge.net/projects/asymptote/files/2.61/
> 

It is here: https://sourceforge.net/projects/asymptote/files/2.61/asymptote-2.61-setup.exe
