### ISSUE TITLE
Version original asygl.js

### ISSUE THREAD

**Issue by ivankokan** [vectorgraphics/asymptote#137]
It would be convenient to version both original and minified asygl.js, what do you think?

**Comment by johncbowman** [comment]
Here's how the versioning works for asygl: there is indeed a version number (1.00) but it is an API version only. This has served us well: over the last four months I have been able to make backwards-compatible online enhancements to the library without incrementing the version number. The version number is currently specified manually by copying the built asygl.js file to asygl-n.nn.js. Once the API is updated (e.g. to support animations) I will have to start maintaining (and posting) both the current version webgl/gl.js and the original webgl/gl-1.00.js source files, so that we don't break existing WebGL files on the internet. The unversioned gl.js always refers to the most up-to-date version of the library (the one shipped with our releases and corresponding to ASYGLVERSION). We don't add an explicit version number to any of our source files; git and our build scripts take care of that for us.
