### ISSUE TITLE
Drawing of hyperbola.  One branch of the hyperbola is rotated after defining a new coordsys

### ISSUE THREAD

**Issue by kinemagician** [vectorgraphics/asymptote#149]
After the new coordsys is defined one branch of the hyperbola is rotated.
Here is the asy script.
----------------------------------  CODE BEGINS HERE -----------------------------------------
//
// Author: kinemagician
//
import graph;
import geometry;
import math;
settings.outformat="eps";
unitsize(1.0cm);
size(10cm);
draw(box((-5,-5),(5,5)), invisible);
// Define hyperbola
//
real a=0.8; // length of major semi-axis
real c=2;  // length linear eccentricity
real b=sqrt(c*c-a*a);
real ang=90;
point orig1=(0,c);
hyperbola H1=hyperbola(orig1, a,b,ang);
draw(H1);
// (Without the following statements the hyperbola is draw correctly!)
// Define a new coordinate system
coordsys R1=cartesiansystem(orig1, i=(1,0), j=(0,-1));
currentcoordsys=R1;
----------------------------------  CODE ENDS HERE -----------------------------------------

**Comment by oguibe** [comment]
Hello

There is a problem in the `init` of hyperbola. More precisely the definition of directrices is not correct when the origin of the `currentcoordsys` if the not the same as the `coordsys` of the point in the definition of the hyperbola. Line 2639
~~~
this.D1 = line(A, A + rotateO(90) * unit(A - this.C));
~~~
the rotation is done in the current coordsys, which is not right.
So I propose to replace this command by
~~~
this.D1 = line(A, A + rotate(90,this.C.coordsys.O) * unit(A - this.C));
~~~
Since modifying the structure of hyperbola is not possible out of `geometry.asy` (or I do not know how to do), I put here `geometry_2.txt`, that you could rename `geometry_2.asy` and then use its by `import geometry_2;` . Of course please use only in your example directory by waiting for an updated version. This version has also a modifed `intersectionpoints` in relation with https://github.com/vectorgraphics/asymptote/issues/154 (line 6578)

[2020_05_03.pdf](https://github.com/vectorgraphics/asymptote/files/4574993/2020_05_03.pdf)

[geometry_2.txt](https://github.com/vectorgraphics/asymptote/files/4575000/geometry_2.txt)

**Comment by johncbowman** [comment]
Applied in commit 1108f83337b6d6f2ac33b9fd0bb0fb47c0578065. Thanks, Olivier!
