### ISSUE TITLE
intersectionpoints hyperbola and line error?

### ISSUE THREAD

**Issue by quanhinh9** [vectorgraphics/asymptote#154]
I have code:

import geometry;
unitsize(1cm);
defaultpen(fontsize(10pt));

point A=(0,0); dot(Label("$A$",align=SW),A);
point B=(7,0); dot(Label("$B$",align=SE),B);
point C=(5,0); dot(Label("$C$",align=SE),C);

circle ca=circle(B,C), cb=circle(C,A); draw(ca^^cb);
hyperbola hp=hyperbola(ca.C,cb.C,abs(ca.r-cb.r)/2);

point [] p=intersectionpoints(hp,line(A,B));

and get error: /usr/local/Cellar/asymptote/2.65/share/asymptote/geometry.asy: 560.3: Divide by zero

How to fix it?

**Comment by oguibe** [comment]
Since I am not able (in a short time) to go deeply in the geometry asy code, here a workaround.
Convert the two branches into paths and then use intersectionpoints.

~~~
import geometry;
unitsize(1cm);
defaultpen(fontsize(10pt));

point A=(0,0); dot(Label("$A$",align=SW),A);
point B=(7,0); dot(Label("$B$",align=SE),B);
point C=(5,0); dot(Label("$C$",align=SE),C);

circle ca=circle(B,C), cb=circle(C,A); draw(ca^^cb);
hyperbola hp=hyperbola(ca.C,cb.C,abs(ca.r-cb.r)/2);
path g1=hp; // First branch
path g2=hyperbola(cb.C,ca.C,abs(ca.r-cb.r)/2); // Second branch
point [] p1=intersectionpoints(line(A,B),g1);
point [] p2=intersectionpoints(line(A,B),g2);
draw(hp);
draw(line(A,B));
dot(p1,red);
dot(p2,red);
~~~

**Comment by oguibe** [comment]
In fact, `geometry.asy` cannot handle segment restricted to one point. For example the code, if `M` is a point, `segment(M,M).A` (s.A is one extremity) gives the same error.
In your case, during the computation, the intersection between the `line(A,B)` and asymptote are the same and a `midpoint(segment(with the same extremities))` produces the error.
It is difficult to modify `geometry.asy` to handle one point segment but it is not difficult to modify
line 6578
~~~
point M = midpoint(segment(A, B));
~~~
by
~~~
 point M = .5 *(A+B);
~~~

**Comment by ivankokan** [comment]
Hi @quanhinh9. Check here: https://github.com/vectorgraphics/asymptote/pull/126#issuecomment-573552189

In general, conics in Asymptote are not fully covered for all degenerate cases but I have that on my TODO list.

**Comment by quanhinh9** [comment]
> Since I am not able (in a short time) to go deeply in the geometry asy code, here a workaround.
> Convert the two branches into paths and then use intersectionpoints.
> 
> ```
> import geometry;
> unitsize(1cm);
> defaultpen(fontsize(10pt));
> 
> point A=(0,0); dot(Label("$A$",align=SW),A);
> point B=(7,0); dot(Label("$B$",align=SE),B);
> point C=(5,0); dot(Label("$C$",align=SE),C);
> 
> circle ca=circle(B,C), cb=circle(C,A); draw(ca^^cb);
> hyperbola hp=hyperbola(ca.C,cb.C,abs(ca.r-cb.r)/2);
> path g1=hp; // First branch
> path g2=hyperbola(cb.C,ca.C,abs(ca.r-cb.r)/2); // Second branch
> point [] p1=intersectionpoints(line(A,B),g1);
> point [] p2=intersectionpoints(line(A,B),g2);
> draw(hp);
> draw(line(A,B));
> dot(p1,red);
> dot(p2,red);
> ```

I don't like casting conic to path, becasue  because its intersection points are incorrect.



> Hi @quanhinh9. Check here: [#126 (comment)](https://github.com/vectorgraphics/asymptote/pull/126#issuecomment-573552189)
> 
> In general, conics in Asymptote are not fully covered for all degenerate cases but I have that on my TODO list.

I write a function that draws a circle that is tangent to three circles. It has errors in some special cases.

**Comment by oguibe** [comment]
Waiting for an update of `geometry.asy`, following my 2nd post, you can add in your example this redefinition of the `intersectionpoints` routine
~~~
point[] intersectionpoints(line l, hyperbola h)
{/*<asyxml></code><documentation>Note that the line 'l' may be a segment by casting.
   intersectionpoints(hyperbola, line) is also defined.</documentation></function></asyxml>*/
  point[] op;
  coordsys R = coordsys(h);
  point A = intersectionpoint(l, h.A1), B = intersectionpoint(l, h.A2);
  point M = .5 *(A+B); //instead of midpoint(segment(A,B))
  bool tgt = M @ h;
  if(tgt) {
    if(M @ l) op.push(M);
  } else {
    real[] eq = changecoordsys(defaultcoordsys, equation(h)).a;
    pair[] tp = intersectionpoints(locate(l.A), locate(l.B), eq);
    point inter;
    for (int i = 0; i < tp.length; ++i) {
      inter = point(R, tp[i]/R);
      if(inter @ l) op.push(inter);
    }
  }
  return op;
}
~~~

**Comment by johncbowman** [comment]
Applied in commit 1108f83. Thanks, Olivier!
