### ISSUE TITLE
Enhance map (Arrays) function 

### ISSUE THREAD

**Issue by ivankokan** [vectorgraphics/asymptote#156]
Instead of current prototype based on only one generic type `T`:
```
T[] map(T f(T), T[] a)
```
it would be useful to enhance it so it can handle two (not necessarily different) generic types `T1` and `T2`, e.g.
```
T2[] map(T2 f(T1), T1[] a)
```

Obviously, such enhancement will be backward-compatible.

Can someone point to the current implementation in the source? Is it https://github.com/vectorgraphics/asymptote/blob/master/builtin.cc?

**Comment by johncbowman** [comment]
Yes, map is defined in builtin.cc and arrayop.h (see arrayFunc and arrayFunc2).
T[] map(T f(T), T[] a) is only defined once an array of type T[] is declared, but there is
no way to anticipate what type T2 the user might want. We can hardwire in special cases,
but I don't think we can do this in general within the current framework.

**Comment by charlesstaats** [comment]
I agree that setting up `T2[] map(T2 f(T1), T1[] a)` for every pair of known types `T1, T2` would be infeasible in the current framework. But I also have found I almost never use `map` because it's missing. (I end up using `sequence` instead, or else building the new array more directly.)

But what if we had a command like `mapdef T2(T1);` that would allow the user to specify what types they want? I think this would make `map` considerably more useful while avoiding the massive function bloat of defining `map` for every pair of known types.

**Comment by johncbowman** [comment]
The mapdef idea is good, but it doesn't appear to be easy to implement. In any case, I think it is cleaner just to use `sequence(new T2(int i) {return f(a[i]);},a.length)` for such cases. This keeps the function signatures more modular (one-dimensional rather than two-dimensional).

**Comment by johncbowman** [comment]
You can always define

`T2[] map(T2 f(T1), T1[] a) {return sequence(new T2(int i) {return f(a[i]);},a.length);};`

To make this more convenient, I have added 

`code map2=quote {T2[] map(T2 f(T1), T1[] a) {return sequence(new T2(int i) {return f(a[i]);},a.length);};};`
in plain.asy so that one can now simply say:

```
typedef int T1;
typedef pair T2;
pair f(int x) {return (x,x^2);};
eval(map2,true);

int[] a={1,2,3};
map(f,a);

```

**Comment by johncbowman** [comment]
This has been further simplified, using the method for writing parametrized code discussed in
https://github.com/vectorgraphics/asymptote/issues/165

```
mapArray("int","pair");

pair f(int x) {return (x,x^2);};
int[] a={1,2,3};
write(map(f,a));

```

**Comment by ivankokan** [comment]
Small format improvement within aa8a5244e46c1d04300513a4107245a3575ceedd.

**Comment by johncbowman** [comment]
Thanks; I committed this change as a separate commit.
