### ISSUE TITLE
import PRC file

### ISSUE THREAD

**Issue by ferdymercury** [vectorgraphics/asymptote#167]
This is a feature request: it would be nice to have the ability to import PRC files into asymptote. Right now, it is only supported the other way (export to PRC).

Related: https://tracker.freecadweb.org/view.php?id=4403

**Comment by ferdymercury** [comment]
So to say, adding  (Deserialize, Read) as the counterparts of the functions (Serialize, Write), etc.

**Comment by johncbowman** [comment]
A few years ago we thought about developing a plugin for PRC content in open-source PDF viewers
by reversing the Asymptote PRC library. Part of the motivation was that existing PRC readers like Adobe Reader (version 9.5.5 still runs natively on linux with i686 compatibility libraries installed) don't remesh on zooming or handle transparency properly.

But the situation has since changed:

1. PRC has too many gaps (most importantly, no vertex-dependent colors for Bezier surfaces) and its development has been abandoned.

2. WebGL provides a widely-available platform-independent alternative that requires no additional software.

3. We are developing a compressed binary format called v3d to replace PRC.

So I don't recommend investing any more effort into PRC.

-- John

**Comment by ferdymercury** [comment]
I understand, but there are still thousands of files, research papers, etc. that are based on PRC files.

I thought it might be interesting to develop a PRC to V3D converter ?

**Comment by johncbowman** [comment]
Yes, that might be a good idea.

**Comment by ferdymercury** [comment]
I reworded the title, in case you want to reopen the issue to keep in mind once there is a 'V3D viewer'
