### ISSUE TITLE
Opacity seems to be broken again…

### ISSUE THREAD

**Issue by cagprado** [vectorgraphics/asymptote#207]
I can't make opacity work, everything will be drawn fully opaque:
```asymptote
size(200);
fill(unitsquare, red+opacity(0.3));
fill(shift(0.3, 0.2)*unitsquare, blue+opacity(0.3));
```
I'm using `ghostscript 9.53.3 (build-3 on Arch Linux)` and here's my `asy -version`:
```
Asymptote version 2.69-9 [(C) 2004 Andy Hammerlindl, John C. Bowman, Tom Prince]

ENABLED OPTIONS:
WebGL    3D HTML rendering
OpenGL   3D OSMesa offscreen rendering
GSL      GNU Scientific Library (special functions)
FFTW3    Fast Fourier transforms
XDR      external data representation (portable binary file format)
CURL     URL support
Readline interactive history and editing
Sigsegv  distinguish stack overflows from segmentation faults
GC       Boehm garbage collector

DISABLED OPTIONS:
```

This is the image generated by the above code:
![Generated Image](https://user-images.githubusercontent.com/910629/107192475-9c647f00-6a28-11eb-91ab-b9277aa120d1.png)

**Comment by johncbowman** [comment]
Probably you just forgot to specify -f pdf (settings.outformat="pdf"). Opacity is only available with pdf output.

**Comment by cagprado** [comment]
My bad! I assumed that using `tex = "xelatex` would suffice and I didn't need to specify the `outformat`. Thanks for the prompt response!

**Comment by clason** [comment]
Hmm, I have the same issue (gs 9.53.3, asy 2.70) using the `asymptote` package for LaTeX and can't for the life of me get opacity working (it used to work with asy included in texlive2020; I'll have to check the exact version).

I tried `asy -f pdf test-1.asy` but that doesn't help. I'd be really grateful if you could point me in the right direction (or tell me whether I should open a new issue for it since it seems related to the LaTeX package)?

**Comment by clason** [comment]
I think I see what the problem is:  `asymptote` (the LaTeX package) adds the following in the preamble:
```
settings.outformat="";
```
which overrides the `-f pdf` argument to `asy`. Changing this to `settings.outformat = "pdf";` makes opacity work again. 

(The same `.asy` files work with `asy` 2.65, though, so I'm a bit confused why it's a problem now.)
