### ISSUE TITLE
lost functionality with 2.69

### ISSUE THREAD

**Issue by markcosgrove** [vectorgraphics/asymptote#218]
Hello,
 
I can’t seem to get 2.69 to execute simple scripts.  I was having so much fun with your program (2.68) and I hope you can get me back on track.  Here’s a simple script that will illustrate my issue:
 
settings.outformat = "svg";
defaultpen(fontsize(20pt));
label("Hello world! $\Delta$",red);
 
With 2.69 I get nothing – no errors – just nothing happens.  The command prompt comes back but no other output.  I also tried outformat=”html” and still no good.
 
Thank you.

**Comment by johncbowman** [comment]
What version of dvisvgm and what operating system are you using?

**Comment by markcosgrove** [comment]
Dvisvgm=2.11.1(64 bit)OS=Win 10 pro (64.bit) And I just noticed my config.asy looks funny: import settings;pdfviewer="acroread";htmlviewer="google-chrome";display="display";animate="animate";libgs=""; Thanks for your support!  From: John BowmanSent: Wednesday, March 10, 2021 12:03 PMTo: vectorgraphics/asymptoteCc: markcosgrove; AuthorSubject: Re: [vectorgraphics/asymptote] lost functionality with 2.69 (#218) What version of dvisvgm and what operating system are you using?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by markcosgrove** [comment]
Dvisvgm=2.11.1(64 bit)
OS=Win 10 pro (64.bit)
 
And I just noticed my config.asy looks funny:
 
import settings;
pdfviewer="acroread";
htmlviewer="google-chrome";
display="display";
animate="animate";
libgs="";
 
Thanks for your support!

**Comment by markcosgrove** [comment]
sorry for msg sent from gmail.

**Comment by johncbowman** [comment]
Your config.asy file looks fine. Due to a cygwin issue, fa3122974baecf2d7743e87705f3b12c913e560b broke svg support under MSWINDOWS in versions 2.66-2.69. Version 2.68 should exhibit the same issue (please check this again; you probably meant 2.65 not 2.68).

The upcoming 2.70 release contains these fixes and will support svg output under MSWINDOWS again:
b9f5aa77eac95d201c88f515a79397e7dc95352c
24b51055076bd6340103cc0bed077932234f49f1
d41e41b63bac1276aa6b5def965acc56188327d4

**Comment by johncbowman** [comment]
P.S. Installing cygwin should fix your problem for now.
