### ISSUE TITLE
pair[] intersectionpoints(path p, path q, real fuzz=-1); such as p is concide with q

### ISSUE THREAD

**Issue by justonlyasy** [vectorgraphics/asymptote#235]
Test code,
```
size(7cm);

path g=(-3,0){dir(45)}..(1,2)..{dir(45)}(0,-1)..(-1,1)..(0,2){dir(135)}..{dir(-135)}(-3,2); // Bezier cubic path
path q=(-3,0)--(1,2)--(0,-1)--(-1,1)--(0,2)--(-3,2); // linear path
transform s=shift(0,-5);
pair[] p = intersectionpoints(g,g);
pair[] t = intersectionpoints(q,q);

write(p.length); // Outputs 52 !? (I think it should be 8)
write(t.length); //  Outputs 6

pen[] stylo={red,green,blue};
stylo.cyclic=true;
dot(g,10bp+green);
dot(s*q,10bp+green);
draw(g);
draw(s*q);
for (int k=0; k<p.length; ++k){ 
    dot(scale(.5)*format("%i",k),p[k],2*dir(k*30),stylo[k]);
}
for (int k=0; k<t.length; ++k){ 
    dot(scale(.5)*format("%i",k),s*t[k],2*dir(k*30),red);
}
shipout(bbox(1mm,white));
```
Why the intersection points of a linear path with itself are different with the intersection points of a cubic spline path with itself?

**Comment by johncbowman** [comment]
The answer to your question is that two different routines are used. When one of the two paths is linear, one can use a purely algebraic computation instead of an iterative bisection method subject to finite recursion depth (fuzz). In addition, both methods are subject to the usual limitations of finite floating-point numerical precision. The algorithms are in https://raw.githubusercontent.com/vectorgraphics/asymptote/HEAD/base/path.cc
We have also tested alternate Bézier clipping algorithms (in asy code; not yet ported to C++); they are not perfect either. 

Note that a Bézier segment between two points can have a different number of self intersections than a straight line with itself.
