### ISSUE TITLE
asymptote windows 10 installation instructions don't work. 

### ISSUE THREAD

**Issue by DeliciousRoastPotato** [vectorgraphics/asymptote#256]
Hi, I tried to install Asymptote 2.7 following the instructions in the manual. The installation completed without incident. I am on Windows 10. 

I tried to use asymptote via the CLI. I could access the help documentation, but none of the other commands produced any diagrams. 

The documentation says that I should install Ghostscript (I did this with the latest version) and GSview. GSview is deprecated, so I tried with Irfran viewer, which can also view ps, eps etc files. However, it still doesn't produce any output. 

While it's likely that I'm missing something, there is at least some degree of bug in that the installation instructions for windows rely on programs that are no longer available. 

Note that I both tested asymptote in the interactive mode and I tried to open the .asy files in the examples folder. Neither option worked.

**Comment by johncbowman** [comment]
You mean Asymptote 2.70, not 2.7. The documentation for the 2.71 release suggests https://www.sumatrapdfreader.org/
as a postscript viewer. Alternatively you can view PDF output by adding the line
`settings.outformat="pdf";`
to your asy examples or using the command-line option `-f pdf`. To use asy from the command line, you may want
to add the asy installation directory to your path (so that you don't have to fully qualify the location of your asy binary on each
invocation). Further help can be obtained from the Asymptote Forum: https://sourceforge.net/p/asymptote/discussion/409349
