### ISSUE TITLE
A bit problem with void texreset();

### ISSUE THREAD

**Issue by justonlyasy** [vectorgraphics/asymptote#268]
As defined in the documentation,

The TEX environment can be reset to its initial state, clearing all macro definitions,
with the function
`void texreset();`

Consider the following example:
```
unitsize(1cm);

texpreamble("\usepackage{starfont}");
path[] h=texpath("\Leo");
filldraw(h,cyan+green,red+dashed+.8bp);

texreset();

texpreamble("\usepackage{marvosym}");
path[] j=texpath("\Leo");
filldraw(shift(5,0)*j,gray,blue+1.5bp);
```
The code above cannot be compiled at http://asymptote.ualberta.ca/ !?

This is my output on my machine (`TeXLive 2021` + `Notepad++` + `Asymptote 2.70`):
![Capture](https://user-images.githubusercontent.com/52594258/132956656-7e6b6e32-7545-4c5c-97ac-da5d32ec83f9.PNG)

The path[] `j` should be
![image](https://user-images.githubusercontent.com/52594258/132956753-e4fa19fd-7456-4b67-b5da-2544cb4f283b.png)

This is a bug or I fail !? What should I do?

Additional,

Consider the following code:
```
texpreamble("\usepackage{utfsym}"); // https://ctan.org/pkg/utfsym?lang=en
unitsize(1cm);

path[] g=texpath("\usym{264C}");
label("\usym{264C}"); // Run normally.

write(g.length); // Outputs: 0 !? <---
```
I don't know why the command `texpath` is not run for this?
Thanks.

**Comment by johncbowman** [comment]
I ran
apt-get install texlive-fonts-extra
on asymptote-server and now your examples work fine there as well.

**Comment by justonlyasy** [comment]
Where should I add `apt-get install texlive-fonts-extra` in my code?

You can please post a runnable code on the Windows system.

**Comment by justonlyasy** [comment]
Please tell me know about the problem of `texreset();`.

I cannot run simultaneously two commands `texpreamble("\usepackage{starfont}");` and `texpreamble("\usepackage{marvosym}");` for the same name of command `\Leo` as described above.

**Comment by johncbowman** [comment]
I only addressed what I thought was the issue, by installing the fonts you asked for on the asymptote server (which runs Ubuntu, not MSWindows):

_The code above cannot be compiled at http://asymptote.ualberta.ca/ !?_

Nothing further needs to be done at your end on that issue.

In the future, it is better to use a separate post for each separate issue.

Now I see that you misunderstood what the texpreamble is. This is the code that appears before the \begin{document}...\end{document} body, before any TeX output. There is only one TeXpreamble.

You are trying to include two incompatible packages (because of the unfortunate use of \newcommand instead of \def in these packages). When you called texreset, you simply cleared the first package from the preamble. So the result you obtained is expected.

If you really want to use incompatible packages like this, you will first need to fix the conflicting definitions,
for example, like this:

`unitsize(1cm);

texpreamble("\usepackage{starfont}");

texpreamble("
\let\starLeo\Leo
\let\Sun\undefined
\let\Moon\undefined
\let\Mercury\undefined
\let\Venus\undefined
\let\Mars\undefined
\let\Jupiter\undefined
\let\Saturn\undefined
\let\Uranus\undefined
\let\Neptune\undefined
\let\Pluto\undefined
\let\Earth\undefined
\let\Zodiac\undefined
\let\Aries\undefined
\let\Aries\undefined
\let\Taurus\undefined
\let\Gemini\undefined
\let\Cancer\undefined
\let\Leo\undefined
\let\Virgo\undefined
\let\Libra\undefined
\let\Scorpio\undefined
\let\Sagittarius\undefined
\let\Capricorn\undefined
\let\Aquarius\undefined
\let\Pisces\undefined
");

texpreamble("\usepackage{marvosym}");

path[] h=texpath("\starLeo");
filldraw(h,cyan+green,red+dashed+.8bp);

path[] j=texpath("\Leo");
filldraw(shift(5,0)*j,gray,blue+1.5bp);
`

**Comment by justonlyasy** [comment]
Thanks for `texpreamble` information.
However,

1. Still be `texreset();`
You can tell about the difference between two following codes (changed positions):
```
unitsize(1cm);

texpreamble("\usepackage{starfont}");
texreset();
texpreamble("\usepackage{marvosym}");

path[] h=texpath("\Leo");
filldraw(h,cyan+green,red+dashed+.8bp);

path[] j=texpath("\Leo");
filldraw(shift(5,0)*j,gray,blue+1.5bp);
```
I completely understand this code! It means `texreset();` will clear `texpreamble("\usepackage{starfont}");` and keep `texpreamble("\usepackage{marvosym}");`, so the output is expected.
![workspace](https://user-images.githubusercontent.com/52594258/132973777-672c47e6-8a42-4c52-aa5e-a8cee62c5342.png)
and
```
unitsize(1cm);

texpreamble("\usepackage{starfont}");

path[] h=texpath("\Leo");
filldraw(h,cyan+green,red+dashed+.8bp);

texreset();
texpreamble("\usepackage{marvosym}");
// OR
/*
texpreamble("\usepackage{marvosym}");
texreset();
*/

path[] j=texpath("\Leo");
filldraw(shift(5,0)*j,gray,blue+1.5bp);
```
I see the output is not exact, Asymptote ignore `texpreamble("\usepackage{marvosym}");` and run `texpreamble("\usepackage{starfont}");` for both `\Leo` commands.
![workspace (1)](https://user-images.githubusercontent.com/52594258/132973918-1370dc1c-3489-4aee-b30b-31798473a8ea.png)

The second code make me confused.

Further, why don't we have `picture pic=currentpicture` for `texpreamble` or `texreset` like
```
texpreamble(picture pic=currentpicture, ...);
texreset(picture pic=currentpicture);
```
?

2.
Please see also `Additional,` in the first comment.

**Comment by justonlyasy** [comment]
For the `2.`, I have a look http://tug.ctan.org/info/symbols/comprehensive/symbols-a4.pdf and in Table 330, I see
`All utfsym symbols are implemented with TikZ graphics, not with a font`. This is the reason why the command `texpath` does not work, isn't this?

**Comment by johncbowman** [comment]
texpreamble affects the entire asy process, not just currentpicture.

Yes, if your symbol is not a font, then of course texpath will not be able to describe it.

**Comment by justonlyasy** [comment]
To finish completely this issue, you can tell a little important information about `1.`, it means the effect of position change of `texreset();`. I really need an explanation.

**Comment by johncbowman** [comment]
The source code in runpicture.in describes precisely what texreset does:
  
 ```
  processDataStruct &pd=processData();
  pd.TeXpipepreamble.clear();
  pd.TeXpreamble.clear();
  pd.tex.pipeclose();
```
