### ISSUE TITLE
Test file won't run

### ISSUE THREAD

**Issue by FrequentErvin** [vectorgraphics/asymptote#363]
Just starting out with Asymptote. I've installed and updated MikTex, installed Ghostscript 10.00.0 and  Asymptote. I made a test file named "test.asy" with a simple draw command inside just to test the program. I'm not sure if I should call the program from cmd but I did and got an error:
![screenshot 81](https://user-images.githubusercontent.com/75392265/211816426-b3b59877-c0cf-4bbb-a3d7-2fd146b24c28.jpg)

**Comment by johncbowman** [comment]
Yes, Asymptote can be called from the command line. Asymptote searches for files in these places:

https://asymptote.sourceforge.io/doc/Search-paths.html#index-search-paths

The message implies that test.asy is not in this search path. Try moving it to your current directory (asy-folder). 

Instead of using MikTeX, we recommend installing TeX from the official distribution https://www.tug.org/texlive/

The GitHub issues list is intended for bug reports and feature requests. Help from other users is available at https://sourceforge.net/p/asymptote/discussion/409349
