### ISSUE TITLE
Missing labels in flattened 3D scene (using settings.render=0) after update to version 2.90.

### ISSUE THREAD

**Issue by stoicbrain** [vectorgraphics/asymptote#467]
I updated my asymptote version on windows 10 x64 from 2.89 to 2.90.
After the update the attached asy-file compiles to a PDF but the Labels are missing.
Going back to version 2.89 everthing works fine.

See the attached asymptote source file and the produced PDFs in the ZIP file.

[AsymptoteLabelProblem.zip](https://github.com/user-attachments/files/16180611/AsymptoteLabelProblem.zip)

**Comment by johncbowman** [comment]
The underlying cause of the problem is that you used `settings.render=0`; simply remove that line from your file.

The line `settings.prc=false`; might as well be removed too since that has been the default for some time now.

Note that `settings.render=0` is an experimental attempt at flattening 3D graphics to postscript; it is not intended for general use and will only produce reasonable results in very special cases, as explained in the documentation. We will nevertheless look into restoring support for labels in this "poor man's" graphics mode.
