### ISSUE TITLE
Black Rectangles on Pixelated Image

### ISSUE THREAD

**Issue by OliverEvans96** [vectorgraphics/asymptote#56]
Hello,

I'm new to Asymptote and I like it quite a bit so far, but I'm having some trouble producing simple 3d graphics.

I've observed the following issue with asymptote from the Arch Linux repository, and now also from github master.

I have the simple script from the tutorial:

`hello3d.asy`
```
settings.outformat = "pdf";
settings.prc = false;
unitsize(3cm);
import three;

draw((0,0,0)--(2,0,0), blue); //x-axis
draw((0,0,0)--(0,2,0), green); //y-axis
draw((0,0,0)--(0,0,2), red); //z-axis

draw(unitsphere);

```

Here is the output of `asy hello3d`:
[hello3d.pdf](https://github.com/vectorgraphics/asymptote/files/1629906/hello3d.pdf)

However, if I set `unitsize(1cm)`, I get:
[hello3d.pdf](https://github.com/vectorgraphics/asymptote/files/1629907/hello3d.pdf)

The two issues I'm observing:
- The black rectangles over the image
- The image seems pixelated, though it should be a vector output?

Any insight into either of these issues would be much appreciated.

Thanks!
Oliver

**Comment by johncbowman** [comment]
1. From the documenation:
If your video card generates unwanted black stripes in the output, try setting the
horizontal and vertical components of the setting `maxtile` to something less than your screen dimensions.

2. For vector graphics you need to remove the line settings.prc = false;
That will generated 3D PRC vector graphics, embedded within a PDF file. However, since
Adobe Reader doesn't remesh on zooming, strictly speaking Adobe Reader isn't a vector graphics viewer.
True (OpenGL) vector graphics is obtained by deleting the line settings.outformat = "pdf".

**Comment by OliverEvans96** [comment]
Wow, thanks so much for the quick response - that helped a lot!

Cheers,
Oliver
