### ISSUE TITLE
Is building even possible without TeX?

### ISSUE THREAD

**Issue by Alhadis** [vectorgraphics/asymptote#76]
When I run `make check` or `make test` after building, I get two different errors. Each suggest that TeX is required to build:

~~~console
$ make check
⋮
../asy -dir ../base pic/*.asy
Testing trans...PASSED.

../asy -dir ../base gs/*.asy
Testing Ghostscript...Cannot execute latex
Please put in a file config.asy

$ make install
⋮
cd doc && /Library/Developer/CommandLineTools/usr/bin/make asy-latex.pdf
pdflatex asy-latex.dtx
make[1]: pdflatex: No such file or directory
make[1]: *** [asy-latex.pdf] Error 1
make: *** [sty] Error 2
~~~

Now, I don't have TeX installed, and I'd prefer to keep it that way. The most binding reason for this is that Homebrew [doesn't support TeX](https://github.com/Homebrew/brew/commit/78507894577ac03587bc7786254f2a54268fd401), and I'd like to have an Asymptote formulae submitted so most macOS users can install this with:

~~~console
$ brew install asymptote
~~~

... because nobody uses MacPorts anymore, and having two package managers installed on the same site can cause "issues".

Unfortunately, the ostensible TeX dependency is probably what's stopped kept Asymptote from being submitted to Homebrew earlier. It's worth noting that Homebrew only concerns itself with non-graphical programs (so GUI-related stuff and PDF documentation are both moot), but TeX is the real roadblock here...

**Comment by mojca** [comment]
(Just to make it clear: I'm not in any way related to asy development, so please don't consider this an official answer. I just replied because I didn't like your justification of the request.)

Unrelated to the technical side of your request / report: please don't request things and justify them with "because nobody uses X any longer". Compared to Office, nobody uses TeX any longer either, and Windows is still far more popular than macOS, and I bet that SolidWorks (or you-name-it) has orders of magnitude more users than asy. (So why would one care about a totally obscure piece of software on OS with relatively low share of users in the first place?)

On the brew's political side (still unrelated to the report): Asymptote is already shipped with MacTeX. If they explicitly kicked out a piece of software (like they did with plenty of other packages) and suggested to replace it with something else, what makes you think that they would be happy to include a subset of that same software that's already included in exactly the suggested replacement? I don't know the answer to this, but that's something that you might want to figure out before spending effort writing something that might be rejected at the end anyway. I do believe that there is a tiny chance that  they might be happy with asymptote alone as it's a tiny piece of software compared to the gigabytes of the "TL monster", but it's not likely it would win the popularity contest either (which was another criterion on which they kicked out plenty of software).

But most important of all: how exactly do you imagine using Asymptote without having TeX installed? You might well be able to skip building asy's documentation, but what then?

**Comment by Alhadis** [comment]
> Asymptote is already shipped with MacTeX

Okay, that's a different story altogether. I assumed the language was less tightly-bound to TeX than it apparently is.

> how exactly do you imagine using Asymptote without having TeX installed?

Generating an SVG version of a 3D data plot? Gluing together stats, justified text, and Wavefront OBJs for some complex, programmatically-generated PDF? Am I wrong to believe these are justified uses of (what appears to be) a general-purpose vector graphics language, or is the language only supposed to be used by TeX authors?

> please don't request things and justify them with "because nobody uses X any longer".

Don't read too far into what I said. I simply meant Homebrew will make Asymptote available to many more developers than MacPorts currently does.

> …relatively low share of users in the first place?

Not sure what you're using as a frame-of-reference, but [~24,894 in-the-wild uses](https://github.com/search?p=3&q=extension%3Aasy+NOT+SymbolType&type=Code) of Asymptote doesn't strike me as "relatively low".

**Comment by mojca** [comment]
> > Asymptote is already shipped with MacTeX
> 
> Okay, that's a different story altogether. I assumed the language was less tightly-bound to TeX than it apparently is.

I'm afraid to give a definite answer since I don't know the internals well enough, but I'm somewhat 97% confident that there is very very little you can do with `asy` without having TeX installed. I'm not sure if you can even place any labels on the graphic, or generate much beyond ghostscript. You can generate awesome proper 3D models, but you mostly cannot even use those without some kind of TeX.

> > how exactly do you imagine using Asymptote without having TeX installed?
> 
> Generating an SVG version of a 3D data plot? Gluing together stats, justified text, and Wavefront OBJs for some complex, programmatically-generated PDF? Am I wrong to believe these are justified uses of

I'm not saying it's not a justified use, I'm just not sure if you can currently do this with asymptote without having TeX installed. The definite answer should be provided by the developer.

> or is the language only supposed to be used by TeX authors?

There's absolutely no need to know any single command in TeX for the sake of being able to draw in asymptote. Even less the need to be the "TeX author" (aka. DEK?) in order to be able to use Asymptote. But if one tool has a dependency that you are reluctant to install on your machine, you very likely won't be able to use that tool.

Properly decoupling asy from TeX might require a hefty pull request from someone ...

> > please don't request things and justify them with "because nobody uses X any longer".
> 
> Don't read too far into what I said. I simply meant Homebrew will make Asymptote available to many more developers than MacPorts currently does.

I understand that providing Asymptote on any given new platform will expose the software to many more new users, and this totally makes sense. However there's absolutely no need to justify this with "nobody uses the existing support".

> > …relatively low share of users in the first place?
> 
> Not sure what you're using as a frame-of-reference,

Mainly cynicism ...

> but [~24,894 in-the-wild uses](https://github.com/search?p=3&q=extension%3Aasy+NOT+SymbolType&type=Code) of Asymptote doesn't strike me as "relatively low".

... but I can guarantee you that there are waaaay more than 25k users of MacPorts (which doesn't strike me as "nobody" either) and that there are way more Windows users than those of HomeBrew. I don't care about frame-of-reference, it just doesn't make any sense to refer to existing support as "there are no users anyway".

**Comment by Alhadis** [comment]
> but I'm somewhat 97% confident that there is very very little you can do with asy without having TeX installed

Yikes. Well, if the language is *that* closely tethered to the system, then I guess it answers my original question. Thanks for the explanation. :)

**Comment by mojca** [comment]
Here's a super old thread answered by the developer: https://sourceforge.net/p/asymptote/discussion/409349/thread/ed91e9b5/
(but I don't believe much has changed since then).

I would say that the core library is pretty generic. What's not so generic at the moment are output routines. This could certainly be changed, but it might require some effort.
