### ISSUE TITLE
Asymptote Opacity Not Working Beyond Ghostscript 9.23

### ISSUE THREAD

**Issue by circosine** [vectorgraphics/asymptote#77]
When compiling a LaTeX document containing an asymptote diagram that specifies an opacity with ```latexmk``` and ```pdflatex```, the compile fails and give the error:
```
Rule 'cusdep asy pdf latex-test-1', function 'asy'
   failed with return code = 256
```
To reproduce this error, use the following document as an example:
```
\documentclass{article}
\usepackage[inline]{asymptote}
\begin{document}
\begin{asy}
settings.outformat="pdf";
settings.prc=false;
settings.render=0;
size(4cm,0);
path3 myarc = rotate(18,Z) * Arc(c=O,
normal=X, v1=-Z, v2=Z, n=10);
surface backHemisphere =
surface(myarc, angle1=0,
angle2=180, c=O, axis=Z, n=10);
surface frontHemisphere = surface(myarc, angle1=180,
angle2=360, c=O, axis=Z, n=10);
draw(backHemisphere, surfacepen=material(white+opacity(0.8),
ambientpen=white), meshpen=gray(0.4));
draw(O--X, blue+linewidth(1pt));
55
draw(frontHemisphere, surfacepen=material(white+opacity(0.8),
ambientpen=white), meshpen=gray(0.4));
\end{asy}
\end{document}
```
The problem is temporarily solved by rolling back Ghostscript to 9.23 or earlier, but it seems that extensions used by asymptote has been removed in the newer versions. It would be great if this issue is addressed in an upcoming release.

**Comment by johncbowman** [comment]
Sorry for taking so long to find a sensible workaround for this Ghostscript bug.
For unknown reasons, the postscript transparency extensions were disabled as part of the security overhaul in recent versions of Ghostscript.

I have finally found a workaround in d98f3793c4df96dcae238312aac889502912872d for this unfortunate decision that does not simply get rid of -dSAFER (even though there should have actually been no security issue in this instance since the postscript to be converted consists of only Asymptote-generated path and stroke commands). 

By the way, from what I could determine #73  was an unrelated Ghostscript installation issue.
